# Generated by Django 4.2.10 on 2024-02-12 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailingModel",
            new_name="Mailing",
        ),
    ]
