# Generated by Django 4.2.10 on 2024-02-12 17:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_rename_mailingmodel_mailing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="filters",
        ),
        migrations.AddField(
            model_name="mailing",
            name="codes_filter",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="tags_filter",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
    ]
