# Generated by Django 4.2.10 on 2024-02-18 08:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_remove_mailing_filters_mailing_codes_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="tags_filter",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
