# Generated by Django 4.2.10 on 2024-02-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("mailing", "0006_alter_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="clients.client",
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
