# Generated by Django 4.2.10 on 2024-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0007_alter_message_client_id_delete_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="celery_task_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(),
        ),
    ]
