# Generated by Django 4.2.10 on 2024-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0008_mailing_celery_task_id_alter_mailing_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
