# Generated by Django 4.2.10 on 2024-02-22 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0009_alter_mailing_celery_task_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="mailing_id",
            new_name="mailing",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="celery_task_id",
        ),
    ]
