# Generated by Django 4.2.10 on 2024-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.PositiveBigIntegerField()),
                ("operator_code", models.IntegerField()),
                ("tag", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
